version: '3'
services:

  sql-server-db:
    container_name: "ltdatabase"
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      SA_PASSWORD: "Welkom12345"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'

  # userservice:
  #   image: ${DOCKER_REGISTRY-}userservice
  #   build:
  #     context: .
  #     dockerfile: UserService/Dockerfile

  # messagingservice:
  #   image: ${DOCKER_REGISTRY-}messagingservice
  #   build:
  #     context: .
  #     dockerfile: MessagingService/Dockerfile

  # imageuploadservice:
  #   image: ${DOCKER_REGISTRY-}imageuploadservice
  #   build:
  #     context: . 
  #     dockerfile: ImageUploadService/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    hostname: jaeger
    restart: always
    ports:
        - "5775:5775/udp" 
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"

  
