version: '3'
services:

  sql-server-db:
    container_name: sql-server-db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
     - "1433:1433"
    environment:
     SA_PASSWORD: "Welkom12345"
     ACCEPT_EULA: "Y"

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

  messagingservice:
    image: ${DOCKER_REGISTRY-}messagingservice
    build:
      context: .
      dockerfile: MessagingService/Dockerfile

  
