version: '3'
services:
    lt-messagingservice:
        image: yarikbrouwer/messagingservice:main
        container_name: 'messagingservice'
        ports:
          - 7080:5000

    lt-userservice:
        image: yarikbrouwer/userservice:main
        container_name: 'userservice'
        ports:
          - 7081:5000

    lt-imageuploadservice:
        image: yarikbrouwer/imageuploadservice:main
        container_name: 'imageuploadservice'
        ports:
          - 7082:5000
    
    lt-frontend:
        image: vite-app:latest
        container_name: 'ltfrontend'
        ports:
          - 5173:5173

    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
          - 5672:5672
          - 15672:15672

  # sql-server-db:
  #   container_name: "ltdatabase"
  #   image: "mcr.microsoft.com/mssql/server:2019-latest"
  #   cap_add:
  #     - SYS_NICE
  #   restart: always
  #   environment:
  #     SA_PASSWORD: "Welkom12345"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - '1433:1433'

  # userservice:
  #   image: ${DOCKER_REGISTRY-}userservice
  #   build:
  #     context: .
  #     dockerfile: UserService/Dockerfile

  # messagingservice:
  #   image: ${DOCKER_REGISTRY-}messagingservice
  #   build:
  #     context: .
  #     dockerfile: MessagingService/Dockerfile

  # imageuploadservice:
  #   image: ${DOCKER_REGISTRY-}imageuploadservice
  #   build:
  #     context: . 
  #     dockerfile: ImageUploadService/Dockerfile


  
