apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: lt-frontend
  name: lt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lt-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/lumbridgetimes-default: "true"
        io.kompose.service: lt-frontend
    spec:
      containers:
        - image: vite-app:latest
          name: ltfrontend
          ports:
            - containerPort: 5173
              hostPort: 5173
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
