apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\yarik\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: lt-frontend
  name: lt-frontend
spec:
  type: LoadBalancer
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  selector:
    io.kompose.service: lt-frontend
status:
  loadBalancer: {}
