apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: lt-imageuploadservice
  name: lt-imageuploadservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lt-imageuploadservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/lumbridgetimes-default: "true"
        io.kompose.service: lt-imageuploadservice
    spec:
      containers:
        - image: lumbridgetimes.azurecr.io/imageuploadservice:latest
          name: imageuploadservice
          ports:
            - containerPort: 5000
              hostPort: 7082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
