apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\yarik\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: lt-imageuploadservice
  name: lt-imageuploadservice
spec:
  ports:
    - name: "7082"
      port: 7082
      targetPort: 5000
  selector:
    io.kompose.service: lt-imageuploadservice
status:
  loadBalancer: {}
