apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lt-messagingservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lt-messagingservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50