apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\yarik\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: lt-messagingservice
  name: lt-messagingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lt-messagingservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\yarik\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/lumbridgetimes-default: "true"
        io.kompose.service: lt-messagingservice
    spec:
      containers:
        - image: yarikbrouwer/messagingservice:main
          name: messagingservice
          ports:
            - containerPort: 5000
              hostPort: 7080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
