apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: lt-messagingservice
  name: lt-messagingservice
spec:
  ports:
    - name: "7080"
      port: 7080
      targetPort: 5000
  selector:
    io.kompose.service: lt-messagingservice
status:
  loadBalancer: {}
