name: Trivy
on:
  push:
    branches:
      - main
jobs:
  fs-scan:
    runs-on:  ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
